# Setup
title:               Tanzim Hoque
tagline:             ''
description:         ''
url:                 https://thoque.co.uk
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Tanzim Hoque
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
